language: go
sudo: false
go:
- 1.x
- 1.11.x
- 1.12.x
- 1.13.x
before_install:
- go get github.com/Masterminds/glide
- go get github.com/go-playground/overalls
- go get github.com/mattn/goveralls
script:
- $GOPATH/bin/glide install
- overalls -project=github.com/mmcloughlin/cite -- -v
after_success:
- goveralls -coverprofile=overalls.coverprofile -service=travis-ci
