package cite

import mock "github.com/stretchr/testify/mock"

// MockLinePredicate is an autogenerated mock type for the LinePredicate type
type MockLinePredicate struct {
	mock.Mock
}

// LineIncluded provides a mock function with given fields: _a0
func (_m *MockLinePredicate) LineIncluded(_a0 int) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
