name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.x
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v -coverprofile=coverage.out ./...
      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
